dataset: "librispeech"

attack_type: 30

path:
  raw_path: "./dataset/LibriSpeech_wav"
  raw_path_test: "./experiments/cloned_speechs"
  wm_speech: "./results/wm_speech"
  ckpt: "./results/ckpt/"
  log_path: "results/log/"

watermark:
  length: 32

optimize:
  batch_size: 1
